# Generated by Django 3.0.4 on 2023-01-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='ShorlURL',
            new_name='ShortURL',
        ),
    ]
