# Generated by Django 3.0.4 on 2023-01-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20230129_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLData',
        ),
    ]
